// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn6xyZem8kAeyz9pfZ0tuaCMXOPd3xsmQ',
    appId: '1:670777604733:web:2f23db1aa35e1cdf684f14',
    messagingSenderId: '670777604733',
    projectId: 'immobila-e811d',
    authDomain: 'immobila-e811d.firebaseapp.com',
    storageBucket: 'immobila-e811d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOr-3BmXvES5sVKHSXatWUZMgijxWDVGo',
    appId: '1:670777604733:android:b92645e8c72794b2684f14',
    messagingSenderId: '670777604733',
    projectId: 'immobila-e811d',
    storageBucket: 'immobila-e811d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm6nFUz5eSx00WJAqLtWZfquQlpWxfo3Q',
    appId: '1:670777604733:ios:145d3f91ec27b22e684f14',
    messagingSenderId: '670777604733',
    projectId: 'immobila-e811d',
    storageBucket: 'immobila-e811d.firebasestorage.app',
    iosBundleId: 'com.example.immobiliakamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm6nFUz5eSx00WJAqLtWZfquQlpWxfo3Q',
    appId: '1:670777604733:ios:145d3f91ec27b22e684f14',
    messagingSenderId: '670777604733',
    projectId: 'immobila-e811d',
    storageBucket: 'immobila-e811d.firebasestorage.app',
    iosBundleId: 'com.example.immobiliakamer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn6xyZem8kAeyz9pfZ0tuaCMXOPd3xsmQ',
    appId: '1:670777604733:web:0c576769fab9fc06684f14',
    messagingSenderId: '670777604733',
    projectId: 'immobila-e811d',
    authDomain: 'immobila-e811d.firebaseapp.com',
    storageBucket: 'immobila-e811d.firebasestorage.app',
  );
}
